build: fix bee hosts for PR preview
ethersphere/gateway-ui pull request #253
Opened 2022-04-22 15:18 UTC by agazso

2022-04-22 15:20 UTC, bee-worker commented
## 🐝 PR preview in Swarm

**Preview URL:** https://bah5acgzauessupeju3xkyaabybqlxtcppaq4n6eoct5yqcl72wycdl4sw4ra.bzz.link
**Swarm Hash:** `a1252a3c89a6eeac0001c060bbcc4f7821c6f88e14fb88097fd5b021af92b722`
**Commit Hash:** f0f9c5d059ec3c7aa66e3f2c24d8db7b3acc291c
**Commit Message:** build: fix bee hosts for PR preview

2022-04-22 17:02 UTC, Cafe137 approved these changes

2022-04-23 03:12 UTC, vojtechsimetka requested changes

2022-04-23 03:12 UTC, vojtechsimetka commented on .github/workflows/check.yaml
> +      REACT_APP_BEE_HOSTS: 'https://api.gateway.ethswarm.org/'
These should still be exposed, not sure why it does not work but will check with devops. Using the `api.gateway.ethswarm` means we lose the frontend optimization. See #218

2022-04-25 12:20 UTC, vojtechsimetka commented on .github/workflows/check.yaml
> +      REACT_APP_BEE_HOSTS: 'https://api.gateway.ethswarm.org/'
```suggestion
      REACT_APP_BEE_HOSTS: 'https://gateway-proxy-bee-0-0.gateway.ethswarm.org/,https://gateway-proxy-bee-1-0.gateway.ethswarm.org/,https://gateway-proxy-bee-2-0.gateway.ethswarm.org/,https://gateway-proxy-bee-3-0.gateway.ethswarm.org/,https://gateway-proxy-bee-4-0.gateway.ethswarm.org/,https://gateway-proxy-bee-5-0.gateway.ethswarm.org/,https://gateway-proxy-bee-6-0.gateway.ethswarm.org/,https://gateway-proxy-bee-7-0.gateway.ethswarm.org/,https://gateway-proxy-bee-8-0.gateway.ethswarm.org/,https://gateway-proxy-bee-9-0.gateway.ethswarm.org/'
```

2022-05-10 07:17 UTC, vojtechsimetka approved these changes

2022-05-10 07:17 UTC, merged